# Generated by Django 4.0.10 on 2023-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utna_module', '0002_utna_indice_ptc_participación_ca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utna_indice_ptc',
            name='Nombre_investigacion',
            field=models.CharField(max_length=250),
        ),
    ]
