# Generated by Django 4.0.10 on 2023-07-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utna_module', '0003_alter_utna_indice_ptc_nombre_investigacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utna_tasa_pe_pertinencia',
            old_name='Carrera',
            new_name='PE',
        ),
    ]
