# Generated by Django 4.0.10 on 2023-07-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utna_module', '0004_rename_carrera_utna_tasa_pe_pertinencia_pe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UTNA_Tasa_Puntaje_ExTSU',
            fields=[
                ('IDTPEXTSU', models.AutoField(primary_key=True, serialize=False)),
                ('Periodo', models.IntegerField()),
                ('p_700_800', models.IntegerField()),
                ('p_801_900', models.IntegerField()),
                ('p_901_1000', models.IntegerField()),
                ('p_1001_1200', models.IntegerField()),
                ('p_1201_1300', models.IntegerField()),
                ('puntaje_satisfactorio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_sobresaliente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utna_module.utna_carreras')),
            ],
        ),
        migrations.CreateModel(
            name='UTNA_Tasa_Puntaje_ExL',
            fields=[
                ('IDTPEXL', models.AutoField(primary_key=True, serialize=False)),
                ('Periodo', models.IntegerField()),
                ('p_700_800', models.IntegerField()),
                ('p_801_900', models.IntegerField()),
                ('p_901_1000', models.IntegerField()),
                ('p_1001_1200', models.IntegerField()),
                ('p_1201_1300', models.IntegerField()),
                ('puntaje_satisfactorio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_sobresaliente', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utna_module.utna_carreras')),
            ],
        ),
    ]
