# Generated by Django 4.0.10 on 2023-07-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utna_module', '0005_utna_tasa_puntaje_extsu_utna_tasa_puntaje_exl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utna_eficiencia_ire',
            name='Indice_desercion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_eficiencia_ire',
            name='Indice_eficiencia_terminal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_eficiencia_ire',
            name='Indice_retencion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_eficiencia_ire',
            name='Indice_titulacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_colocacion',
            name='Colocados',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_colocacion',
            name='Egresados',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_colocacion',
            name='Indice_colocacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_ptc',
            name='Estado_investigacion',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_ptc',
            name='Nombre_investigacion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_ptc',
            name='Nombre_profesor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_ptc',
            name='Tipo_profesor',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Actividades_arte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Actividades_crecimiento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Alimentos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Asesoria_academica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Bibliteca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Bolsa_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Conectivida',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Espacio_expresion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Estimulos_desempeno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Fomento_salud',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Indice_satisfaccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Instalaciones',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Laboratorio_computo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Laboratorio_practica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Orientacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Salud_externa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Salud_interna',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Seguridad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Traslado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_indice_servicios',
            name='Tutoria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Calificacion_MEB5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Conocimiento_prof',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Dominio_prob_lab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Experiencia_practica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Indice_satisfaccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Infraestructura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Laboratorios_talleres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Op_preparacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Bolsa_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Calificacion_MEB5',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Conocimiento_prof',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Dominio_prob_lab',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Experiencia_practica',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Indice_satisfaccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Infraestructura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Laboratorios_talleres',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Op_estadia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Op_preparacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_iseg_tsu',
            name='Trabaja_lugar_estadia',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Calificacion_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Capacidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Creatividad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Cumple_req',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Indice_satisfaccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Manejo_equipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Op_grado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Op_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_l',
            name='Solucion_prob',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Calificacion_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Capacidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Creatividad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Cumple_req',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Indice_satisfaccion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Manejo_equipo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Op_grado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Op_trabajo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_isem_tsu',
            name='Solucion_prob',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_acreditacion',
            name='Fecha_acreditacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_acreditacion',
            name='Fecha_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_acreditacion',
            name='Tipo_acreditacion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_cobertura',
            name='Incremento_matricula',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_docentes',
            name='Doc_perfil_adecuado',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_docentes',
            name='Exp_Lab_pertinente',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_docentes',
            name='No_docentes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_docentes',
            name='Tasa_docentes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_alumnos',
            name='Matricula',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_alumnos',
            name='No_alum_viajaron',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_alumnos',
            name='Tasa_movilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_docentes',
            name='Matricula',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_docentes',
            name='No_doc_viajaron',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_mov_docentes',
            name='Tasa_movilidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_pe_asat',
            name='Realizacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_pe_asat',
            name='Vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_pe_pertinencia',
            name='Fecha_elaboracion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='p_1001_1200',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='p_1201_1300',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='p_700_800',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='p_801_900',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='p_901_1000',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='puntaje_satisfactorio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egel',
            name='puntaje_sobresaliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='p_1001_1200',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='p_1201_1300',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='p_700_800',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='p_801_900',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='p_901_1000',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='puntaje_satisfactorio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_egetsu',
            name='puntaje_sobresaliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='p_1001_1200',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='p_1201_1300',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='p_700_800',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='p_801_900',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='p_901_1000',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='puntaje_satisfactorio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_exl',
            name='puntaje_sobresaliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='p_1001_1200',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='p_1201_1300',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='p_700_800',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='p_801_900',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='p_901_1000',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='puntaje_satisfactorio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='utna_tasa_puntaje_extsu',
            name='puntaje_sobresaliente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
