# Generated by Django 4.0.10 on 2023-07-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utna_module', '0006_alter_utna_eficiencia_ire_indice_desercion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utna_iseg_l',
            name='Trabaja_lugar_estadia',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5, null=True),
        ),
    ]
