# Generated by Django 4.0.10 on 2023-06-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Cargo',
            field=models.CharField(choices=[('RECTOR', 'Rector'), ('PLANEACION', 'Planeacion')], max_length=10),
        ),
    ]
