# Generated by Django 4.0.10 on 2023-06-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_module', '0002_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='Cargo',
            field=models.CharField(choices=[('RECTOR', 'Rector'), ('PLANEACION', 'Planeacion'), ('DIRECTOR', 'Director')], max_length=10),
        ),
    ]
